{
  "name": "approvalms-api",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": "10.x.x",
    "npm": ">=6.0.0"
  },
  "scripts": {
    "start": "node start.js"
  },
  "dependencies": {
    "@babel/cli": "^7.5.0",
    "@babel/core": "^7.5.4",
    "@babel/node": "^7.5.0",
    "@babel/plugin-transform-regenerator": "^7.4.5",
    "@babel/plugin-transform-runtime": "^7.4.4",
    "@babel/preset-env": "^7.5.5",
    "@babel/register": "^7.4.4",
    "@babel/runtime": "^7.5.5",
    "@sap/approuter": "^6.0.1",
    "@sap/cloud-sdk-vdm-purchase-order-service": "^1.5.0",
    "@sap/hana-client": "^2.4.144",
    "@sap/hdbext": "^6.0.1",
    "@sap/xsenv": "^2.0.0",
    "@sap/xssec": "^2.2.2",
    "JSONStream": "^1.3.5",
    "async": "^3.1.0",
    "axios": "^0.19.0",
    "axios-oauth-client": "^1.1.1",
    "axios-token-interceptor": "^0.1.0",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-regenerator": "^6.26.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-jest": "^24.6.0",
    "brain.js": "^2.0.0-beta.1",
    "cf-nodejs-logging-support": "^5.2.6",
    "cfenv": "^1.2.2",
    "circular-json": "^0.5.9",
    "cors": "^2.8.5",
    "country-code-lookup": "0.0.17",
    "create-react-native-app": "^2.0.2",
    "email-templates": "^6.0.0",
    "event-stream": "^4.0.1",
    "express": "^4.17.1",
    "express-middleware": "^3.4.1",
    "express-xml-bodyparser": "^0.3.0",
    "fs": "0.0.1-security",
    "globally": "0.0.0",
    "moment": "^2.24.0",
    "mongoose": "^5.3.13",
    "nodemailer": "^6.3.0",
    "passport": "^0.4.0",
    "path": "^0.12.7",
    "predix-uaa-client": "^1.3.7",
    "pusher": "^2.2.0",
    "react": "^16.6.3",
    "react-country-flag": "^2.3.0",
    "react-scripts": "^3.0.1",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/plugin-transform-runtime": "^7.4.4",
    "nodemon": "^1.19.1"
  }
}
